services:
  postgres:
    image: postgres:15
    container_name: wallet-postgres
    environment:
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpass
      POSTGRES_DB: walletdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: wallet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
      SPRING_DATASOURCE_USERNAME: walletuser
      SPRING_DATASOURCE_PASSWORD: walletpass
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  postgres_data: