spring:
  application:
    name: wallet.app
  datasource:
    url: jdbc:postgresql://localhost:5434/walletdb
    username: walletuser
    password: walletpass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      leak-detection-threshold: 10000
      maximum-pool-size: 50
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 8080
  servlet:
    context-path: /api/v1